<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <AssemblyName>STranslate.Plugin.Tts.VoyceTTS</AssemblyName>
    <RootNamespace>STranslate.Plugin.Tts.VoyceTTS</RootNamespace>
    <RepositoryUrl>https://github.com/iceblyte/STranslate.Plugin.Tts.VoyceTTS</RepositoryUrl>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <OutputPath>..\..\..\..\.artifacts\Debug\Plugins\STranslate.Plugin.Tts.VoyceTTS\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <OutputPath>.artifacts\</OutputPath>
    <EnableAutoPackage>true</EnableAutoPackage>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="STranslate.Plugin" Version="1.0.15" />
    <PackageReference Include="System.Speech" Version="10.0.0" GeneratePathProperty="true" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="plugin.json" CopyToOutputDirectory="Always" />
    <Content Include="icon.png" CopyToOutputDirectory="Always" />
    <None Include="icon.svg" />
    <Content Include="Languages\*.*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="VoyceTTS.Tests\**\*.cs" />
  </ItemGroup>
  <Target Name="CopySystemSpeech" AfterTargets="Build" BeforeTargets="PackageAsSpkg">
    <Copy SourceFiles="$(PkgSystem_Speech)\runtimes\win\lib\net10.0\System.Speech.dll" DestinationFolder="$(OutputPath)" />
  </Target>
</Project>
